"""Add PublishedSchedule read model

Revision ID: 6ec8a635c353
Revises: b65d5f6dda81
Create Date: 2026-09-10 10:16:19.215830

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6ec8a635c353'
down_revision: Union[str, None] = 'b65d5f6dda81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timetable_version_id', sa.UUID(), nullable=True),
    sa.Column('exam_timetable_version_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('staff_profile_id', sa.UUID(), nullable=True),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('cohort_name', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('slot_span', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_schedule_cohort_id'), 'published_schedule', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_published_schedule_course_id'), 'published_schedule', ['course_id'], unique=False)
    op.create_index(op.f('ix_published_schedule_exam_timetable_version_id'), 'published_schedule', ['exam_timetable_version_id'], unique=False)
    op.create_index(op.f('ix_published_schedule_room_id'), 'published_schedule', ['room_id'], unique=False)
    op.create_index(op.f('ix_published_schedule_staff_profile_id'), 'published_schedule', ['staff_profile_id'], unique=False)
    op.create_index(op.f('ix_published_schedule_tenant_id'), 'published_schedule', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_published_schedule_timetable_version_id'), 'published_schedule', ['timetable_version_id'], unique=False)
    op.create_index(op.f('ix_academic_term_tenant_id'), 'academic_term', ['tenant_id'], unique=False)
    op.execute("ALTER TABLE assignment DROP CONSTRAINT IF EXISTS assignment_locked_by_fkey")
    # op.create_foreign_key(None, 'assignment', 'identity', ['locked_by'], ['id'])
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_batch_tenant_id'), 'batch', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_campus_tenant_id'), 'campus', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cohort_tenant_id'), 'cohort', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_constraint_rule_tenant_id'), 'constraint_rule', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_course_tenant_id'), 'course', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_department_tenant_id'), 'department', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_elective_section_tenant_id'), 'elective_section', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_eligibility_tenant_id'), 'eligibility', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_enrollment_record_tenant_id'), 'enrollment_record', ['tenant_id'], unique=False)
    op.add_column('exam_session', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_exam_session_tenant_id'), 'exam_session', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_exam_timetable_version_tenant_id'), 'exam_timetable_version', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_exception_calendar_tenant_id'), 'exception_calendar', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_period_template_tenant_id'), 'period_template', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_room_tenant_id'), 'room', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_staff_availability_block_tenant_id'), table_name='staff_availability_block')
    op.create_index(op.f('ix_staff_profile_tenant_id'), 'staff_profile', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_student_profile_tenant_id'), 'student_profile', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_substitution_log_tenant_id'), 'substitution_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_timetable_version_tenant_id'), 'timetable_version', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_version_tenant_id'), table_name='timetable_version')
    op.drop_index(op.f('ix_substitution_log_tenant_id'), table_name='substitution_log')
    op.drop_index(op.f('ix_student_profile_tenant_id'), table_name='student_profile')
    op.drop_index(op.f('ix_staff_profile_tenant_id'), table_name='staff_profile')
    op.create_index(op.f('ix_staff_availability_block_tenant_id'), 'staff_availability_block', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_room_tenant_id'), table_name='room')
    op.drop_index(op.f('ix_period_template_tenant_id'), table_name='period_template')
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_index(op.f('ix_exception_calendar_tenant_id'), table_name='exception_calendar')
    op.drop_index(op.f('ix_exam_timetable_version_tenant_id'), table_name='exam_timetable_version')
    op.drop_index(op.f('ix_exam_session_tenant_id'), table_name='exam_session')
    op.drop_column('exam_session', 'tenant_id')
    op.drop_index(op.f('ix_enrollment_record_tenant_id'), table_name='enrollment_record')
    op.drop_index(op.f('ix_eligibility_tenant_id'), table_name='eligibility')
    op.drop_index(op.f('ix_elective_section_tenant_id'), table_name='elective_section')
    op.drop_index(op.f('ix_department_tenant_id'), table_name='department')
    op.drop_index(op.f('ix_course_tenant_id'), table_name='course')
    op.drop_index(op.f('ix_constraint_rule_tenant_id'), table_name='constraint_rule')
    op.drop_index(op.f('ix_cohort_tenant_id'), table_name='cohort')
    op.drop_index(op.f('ix_campus_tenant_id'), table_name='campus')
    op.drop_index(op.f('ix_batch_tenant_id'), table_name='batch')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.create_foreign_key(op.f('assignment_locked_by_fkey'), 'assignment', 'identity', ['locked_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_assignment_tenant_id'), table_name='assignment')
    op.drop_index(op.f('ix_academic_term_tenant_id'), table_name='academic_term')
    op.drop_index(op.f('ix_published_schedule_timetable_version_id'), table_name='published_schedule')
    op.drop_index(op.f('ix_published_schedule_tenant_id'), table_name='published_schedule')
    op.drop_index(op.f('ix_published_schedule_staff_profile_id'), table_name='published_schedule')
    op.drop_index(op.f('ix_published_schedule_room_id'), table_name='published_schedule')
    op.drop_index(op.f('ix_published_schedule_exam_timetable_version_id'), table_name='published_schedule')
    op.drop_index(op.f('ix_published_schedule_course_id'), table_name='published_schedule')
    op.drop_index(op.f('ix_published_schedule_cohort_id'), table_name='published_schedule')
    op.drop_table('published_schedule')
    # ### end Alembic commands ###
