"""Add batch_membership

Revision ID: da27bdf843b4
Revises: 9452e804bdfc
Create Date: 2026-09-09 00:46:40.189509

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'da27bdf843b4'
down_revision: Union[str, None] = '9452e804bdfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_membership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_membership_tenant_id'), 'batch_membership', ['tenant_id'], unique=False)
    op.alter_column('elective_section', 'term_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('elective_section', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student_profile', 'external_student_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student_profile', 'cohort_id',
               existing_type=sa.UUID(),
               nullable=False)

    # Add RLS to batch_membership
    op.execute("ALTER TABLE batch_membership ENABLE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation ON batch_membership "
        "USING (tenant_id = current_setting('app.tenant_id')::uuid);"
    )
    op.execute("ALTER TABLE batch_membership FORCE ROW LEVEL SECURITY;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop RLS
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON batch_membership;")
    op.execute("ALTER TABLE batch_membership DISABLE ROW LEVEL SECURITY;")

    op.alter_column('student_profile', 'cohort_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('student_profile', 'external_student_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('elective_section', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('elective_section', 'term_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_batch_membership_tenant_id'), table_name='batch_membership')
    op.drop_table('batch_membership')
    # ### end Alembic commands ###
